server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567890
    url: jdbc:mysql://localhost:3306/db_flowermall?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8

#mybatis-plus:
#  mapper-locations: /mapper/**.xml
